export const DEFAULT_EXPENSE_CATEGORIES = [
    "Eating out",
    "Groceries",
    "Car Insurance",
    "Car - Gasoline",
    "Subscriptions (Netflix, Disney+, Spotify, Anthropic)",
    "Kids activities (capoeira, theater)",
    "Gas Co",
    "Electric",
    "Arnona",
    "Water",
    "Rent/Mortgage",
    "School and tzaharon",
    "TV/Internet",
    "Cellular",
    "Health insurance",
    "Pension",
    "Keren Hishtalmut",
    "Insurance other (life, disability, apartment)",
    "Pets (vet, food, insurance, pet store)",
    "Personal spending",
    "Clothes & shoes",
    "Fun & Entertainment (Movies, museums, etc)",
    "Medical/pharmacy (doctor, dentist, pharmacy, kupat holim)",
    "Gifts",
    "Home (from TV's to lightbulbs)",
    "Transportation other (parking, public transit)",
    "Other",
];

export const DEFAULT_INCOME_CATEGORIES = [
    "Salary",
    "Freelance",
    "Government benefits",
    "Rental income",
    "Other income",
];